### ISSUE TITLE
Solidarity (Not an issue)

### ISSUE THREAD

**Issue by sammypanda** [quatquatt/RebuildButLessDumb#1]
This is just a comment >< I hope you don't mind it as an issue, i couldn't find any other way to message.

I'm literally doing the same thing with my nix config. I made it when nix flakes weren't really explained so it's this weird hybrid of the old configuration style and a flake. I felt like rescuing my one n changing each thing, but so much has to change for it to be good that i'm kinda settled on just restarting xD (also there are so many little gotchas in nix unfortunately, like "oh no don't pass through pkgs with specialArgs cuz it only half works" n blabla, Nix is a trainwreck a bit in that way hehe).

Anyway, good luck!

**Comment by llakala** [comment]
> This is just a comment >< I hope you don't mind it as an issue, i couldn't find any other way to message.
> 
> I'm literally doing the same thing with my nix config. I made it when nix flakes weren't really explained so it's this weird hybrid of the old configuration style and a flake. I felt like rescuing my one n changing each thing, but so much has to change for it to be good that i'm kinda settled on just restarting xD (also there are so many little gotchas in nix unfortunately, like "oh no don't pass through pkgs with specialArgs cuz it only half works" n blabla, Nix is a trainwreck a bit in that way hehe).
> 
> Anyway, good luck!

Thanks so much!! I'm working on a blog right now which will include some contact info. And yes, there are so many little edge cases. Every time I run into an issue, I try to over-comment it and put the solution *somewhere*, to benefit those that come after me. Hopefully, when I get the blog working, I'll be able to share my solutions as resources. 

Thanks for the support! Good luck with everything Nix-y :33
