### ISSUE TITLE
Trying rbld with nix config that doesn't live in /etc/nixos fails

### ISSUE THREAD

**Issue by NovaViper** [quatquatt/RebuildButLessDumb#12]
I do the following and the command ends up failing with the log below:
```
❯ rbld -d $FLAKE
building the system configuration...
error:
       … while evaluating the attribute 'config.system.build.toplevel'
         at /nix/store/9smdm0q35nk0zggr6p9ib4ij710asqsj-source/lib/modules.nix:334:9:
          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          335|         _module = checked (config._module);

       … while calling the 'seq' builtin
         at /nix/store/9smdm0q35nk0zggr6p9ib4ij710asqsj-source/lib/modules.nix:334:18:
          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I)
┏━ 1 Errors:
┃ error:
┃        … while evaluating the attribute 'config.system.build.toplevel'
┃          at /nix/store/9smdm0q35nk0zggr6p9ib4ij710asqsj-source/lib/modules.nix:334:9:
┃           333|         options = checked options;
┃           334|         config = checked (removeAttrs config [ "_module" ]);
┃              |         ^
┃           335|         _module = checked (config._module);
┃
┃        … while calling the 'seq' builtin
┃          at /nix/store/9smdm0q35nk0zggr6p9ib4ij710asqsj-source/lib/modules.nix:334:18:
┃           333|         options = checked options;
┃           334|         config = checked (removeAttrs config [ "_module" ]);
┃              |                  ^
┃           335|         _module = checked (config._module);
┃
┃        (stack trace truncated; use '--show-trace' to show the full, detailed trace)
┃
┃        error: file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I)
┣━━━
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 23:54:33 after 0s
```

🤔 I theorize it's because I don't have my flake set under the NIX_PATH variable, instead of opting for my own custom FLAKE variable (this is because I wasn't sure how exactly NIX_PATH works and really hadn't found any documentation about it at all 😅 ). Usually when I run the `nixos-rebuild` command I always append it with `--flake $FLAKE`

**Comment by llakala** [comment]
Fascinating. I have an idea for a fix.

**Comment by llakala** [comment]
@NovaViper I think I have a fix. Could you point your flake input to the branch I just made, like this: 

`rbld.url = "github:llakala/rebuild-but-less-dumb/rbld-in-separate-directory";`

I just hadn't been using the `--flake` argument with `nixos-rebuild`. Now that I am, it should work perfectly.

(I'll merge this branch into main once I confirm with you that this fixes it)

**Comment by NovaViper** [comment]
That fixed it!

**Comment by NovaViper** [comment]
🤔 But huh.. now running `unify` results in this
```
❯ unify -d $FLAKE
jq: error (at flake.lock:825): Cannot index object with null
```

Edit: Ah nvm, disregard this. I had completely forgotten about the `-i` parameter

**Comment by llakala** [comment]
> 🤔 But huh.. now running `unify` results in this
> 
> ```
> ❯ unify -d $FLAKE
> jq: error (at flake.lock:825): Cannot index object with null
> ```
> 
> Edit: Ah nvm, disregard this. I had completely forgotten about the `-i` parameter

Yeah, this is an error I want to make clearer, see #8. Anyways, I'll merge in the branch to main, so you can point your flake input at main again.
